import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { gql } from "@apollo/client";
import client from "../apollo-client";
import Users from "../component/Users";

/*export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
    query Users{
      getAllUsers {
        RUT
        name
        email
        password
        especialidad
        Date
        edad
      }
    }
    `,
  });

  return {
    props: {
      users: data.getAllUsers,
    },
 };
}
*/
export default function Home({ users }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <div className={styles.grid}>
  <h1>MARCIANEKE
  </h1>
</div><div><h2>Que PAZA!</h2></div>
      </main>

      <footer className={styles.footer}>
        Que saben de corte, si nosotros somoh el corte ahja!
      </footer>
    </div>
  )
}
