import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { gql } from "@apollo/client";
import client from "../apollo-client";

export async function getServerSideProps() {
  const { data } = await client.query({
    query: gql`
    query Users{
      getAllUsers {
        RUT
        name
        email
        password
        especialidad
        Date
        edad
      }
    }
    `,
  });

  return {
    props: {
      users: data.getAllUsers,
    },
  };
}

export default function Home({ users }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <div className={styles.grid}>
  {users.map((user) => (
    <div key={users.id} className={styles.card}>
      <h3>{user.name} {user.especialidad}</h3>
      <h3>{user.email}</h3>
    </div>
  ))}
</div>
      </main>
  <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
